
# SEO settings
title: Azure Sky
description: "Blog test"
keywords: "machine learning, NLP, blog"
url: http://bgshin.github.io
# baseurl: "/blog"
baseurl: null

google_analytics: 
repo: http://bgshin.github.io
disqus_shortname: 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Bonggun Shin
  job      : PhD Student
  bio      : "Interested in Machine learning and NLP."
  thumb    : /images/author.jpg
  email    : bonggun.shin@emory.edu
  url      : http://bgshin.github.io
  github   : http://github.com/bgshin
  twitter  : 
  facebook : http://facebook.com/bgshin
  linkedin : http://linkedin.com/in/bgshin

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@nandomoreirame"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
