# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bonggun Shin
email: bonggun.shin@emory.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  bgshin

# Build settings
# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

markdown: redcarpet
redcarpet:
  extensions: ["tables", "strikethrough", "superscript", "with_toc_data"]



# markdown: kramdown
# kramdown:
#   input: GFM

# highlighter: rouge
  # syntax_highlighter: rouge
# highlighter: pygments
# permalink: pretty
# relative_permalinks: false
